package ast.enums;

public enum BuiltInFunction
{
    ABS, ASIN, ACOS, ATAN, COS, FLIP, FLOAT, INTEGER, LEN, INT, LOG, PI, PRINT, POW, UNIFORMFLOAT, UNIFORMNAT,
    UNIFORMPERM, SIN, SINGLETONSET, SQRT, TAN
}
