package ast.enums;

public enum BuiltInMethod
{
    AT, DELETE, END, FIRST, INSERT, KEYS, POPBACK, POPFRONT, PUSHBACK, PUSHFRONT, REMOVE, REMOVEALLEQTO, REMOVEAT,
    SIZE, SPLIT, TOPBACK, TOPFRONT, UPDATE
}
