package ast.enums;

public enum Operator
{
    IFELSE, LOGICALOR, LOGICALAND, IN, EQUAL, NOTEQUAL, LOWER, LOWEREQ, GREATER, GREATEREQ,
    UNION, INTERSECT, SETSUBTRACT, BITWISEOR, BITWISEAND, BITWISEXOR, SHIFTLEFT, SHIFTRIGHT,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, PLUSPLUSLEFT, MINUSMINUSLEFT, POSITIVE, NEGATIVE,
    NOT, PLUSPLUSRIGHT, MINUSMINUSRIGHT, BRACKET, DOT,

    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN, MOD_ASSIGN, LSHIFT_ASSSIGN,
    RSHIFT_ASSIGN, LOR_ASSIGN, LAND_ASSIGN
}
