package visitor;

public enum Operator
{
    IFELSE, LOGICALOR, LOGICALAND, IN, EQUAL, NOTEQUAL, LOWER, LOWEREQ, GREATER, GREATEREQ,
    UNION, INTERSECT, SETSUBTRACT, BITWISEOR, BITWISEAND, BITWISEXOR, SHIFTLEFT, SHIFTRIGHT,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, MOD, PLUSPLUSLEFT, MINUSMINUSLEFT, POSITIVE, NEGATIVE,
    NOT, PLUSPLUSRIGHT, MINUSMINUSRIGHT, BRACKET
}
