package ro.uaic.info.alk.visitor.ifaces;

/**
 * Interface to be implemented by structures that can be visited. This
 * is usually about {@code AST}.
 */
public interface Visitable
{
    /**
     * The core method that allows visitors to visit this structured.
     *
     * @param   visitor
     *          The visitor that is used for visiting.
     *
     * @return  The payload generated by the visitor.
     */
    <T> T accept(VisitorIface<T> visitor);
}
